### ISSUE TITLE
[1주차] 1. 운영체제 개요

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#1]
## 챕터 소개
- 강의를 소개하고 운영체제의 정의, 목적, 컴퓨터 시스템 내에서의 기능이 무엇인지 알아본다.
- 운영체제의 기능인 CPU 스케줄링, 메모리 관리, 디스크 스케줄링과 운영체제의 종류에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

**🗓기한 : `2월 9일  수요일 21:00` 까지 공부 정리한 내용 댓글로 남기기**

**Comment by seyoung755** [comment]
1주차 학습 정리 업로드합니다! 
[운영체제 개요](https://velog.io/@seyoung755/220206-TIL)

**Comment by ak2j38** [comment]
1주차 학습정리 블로그 링크입니다!
https://velog.io/@ak2j38/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-1.-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B0%9C%EC%9A%94

**Comment by CMSSKKK** [comment]
1.운영체제 개요 업로드합니다.
[운영체제 개요](https://velog.io/@cmsskkk/01.-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C%EC%9D%98-%EA%B0%9C%EC%9A%94)

**Comment by jinan159** [comment]
1주차 학습정리 업로드합니다~!
https://jwkim96.tistory.com/212

**Comment by nak253** [comment]
1주차 학습정리 링크입니다
https://phase-bow-938.notion.site/e0f54d8e6fa14a40ac726ffb663855a3

**Comment by devjun10** [comment]
[1주차 학습정리](https://cookie-tin-8ec.notion.site/8441c4889ed2479c9a91c8b9ed887fd4) 입니다.

**Comment by leekm0310** [comment]
1주차 학습정리 링크입니다.
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-1%EC%A3%BC%EC%B0%A8-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B0%9C%EC%9A%94

**Comment by Louie-03** [comment]
[1주차 학습정리](https://velog.io/@louie/1%EC%A3%BC%EC%B0%A8-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B0%9C%EC%9A%94)입니다.
