### ISSUE TITLE
[10주차] 12. 파일시스템

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#10]
## 12. 파일시스템

- 파일시스템의 기초, 디렉토리 구조, 파일의 접근권한 보호 등에 대해 알아본다.
- 파일시스템의 파일 할당 방법, 파일시스템의 기초 등에 대해 학습한다.
- Unix와 FAT 파일시스템의 구조와 파일을 관리하는 방법에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 4월 13일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by ak2j38** [comment]
파일시스템 내용 정리입니다!
[파일시스템](https://velog.io/@ak2j38/운영체제-스터디-10.-파일시스템)

**Comment by seyoung755** [comment]
10주차 내용 업로드합니다!
https://velog.io/@seyoung755/운영체제-10주차-파일-시스템

**Comment by CMSSKKK** [comment]
10주차 업로드합니다.
[파일시스템](https://velog.io/@cmsskkk/%ED%8C%8C%EC%9D%BC-%EC%8B%9C%EC%8A%A4%ED%85%9C)

**Comment by leekm0310** [comment]
내용정리 업로드 합니다
[파일시스템](https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-10%EC%A3%BC%EC%B0%A8-%ED%8C%8C%EC%9D%BC-%EC%8B%9C%EC%8A%A4%ED%85%9C)

**Comment by jinan159** [comment]
파일시스템 학습정리 입니다
https://jwkim96.tistory.com/250

**Comment by devjun10** [comment]
[파일시스템 학습정리](https://knowing-lemon-7bd.notion.site/e5f9fd0922c94ffe9aec1086a897d84b)입니다.
