### ISSUE TITLE
[11주차] 13. 입출력 시스템

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#11]
## 13. 입출력 시스템

- 디스크 매니지먼트와 스케줄링에 대해 알아본다.
- Ext4 파일시스템, 저널링, 버퍼캐시 알고리즘에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 4월 20일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by ak2j38** [comment]
11주차 내용정리입니다.
[입출력 시스템](https://velog.io/@ak2j38/운영체제-스터디-11.-입출력-시스템)

**Comment by seyoung755** [comment]
11주차 내용입니다
https://velog.io/@seyoung755/운영체제-11주차-입출력-시스템

**Comment by leekm0310** [comment]
11주차 정리입니다
https://velog.io/@becolorful/운영체제-스터디-11주차-입출력시스템

**Comment by nak253** [comment]
11주차 학습정리입니다.
[입출력시스템1](https://phase-bow-938.notion.site/6ad257e242804e4ab5b3cdd8d6bd3acd)
[입출력시스템2](https://phase-bow-938.notion.site/Ext-91bf7f1417ed4c7183ee22548f4f8870)

**Comment by CMSSKKK** [comment]
[11주차 학습정리입니다.](https://velog.io/@cmsskkk/%EC%9E%85%EC%B6%9C%EB%A0%A5-%EC%8B%9C%EC%8A%A4%ED%85%9C)

**Comment by jinan159** [comment]
11주차 학습정리입니다.
https://jwkim96.tistory.com/250

**Comment by devjun10** [comment]
[11주차 학습정리](https://www.notion.so/2a3e1e8cfb4b4d59a717265e53fefca1) 입니다.
