### ISSUE TITLE
[2주차] 2. 컴퓨터시스템의 구조

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#2]
## 챕터 소개
- 운영체제의 종류, 특히 공개/비공개 소프트웨어에 대해 구체적으로 알아본다.
- 운영체제의 정의, 목적, 분류, 예, 구조를 알아보고, 과목 성격이 개발자 관점의 운영체제 이해임을 이해한다.
- 컴퓨터 시스템의 구조와 관련해, 프로그램 수행에 Mode bit, Timer 등이 어떻게 작동하는지 알아본다.
- 인터럽트가 운영체제를 구동시키는 원리와 인터럽트의 한 종류인 시스템콜에 대해 알아본다.
- 동기식/비동기식 입출력에서의 인터럽트, DMA를 이용한 인터럽트 조절에 대해 알아본다.
- 계층구조에 의해 I/O에서 입출력명령어가 다름을 이해한다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

**🗓기한 : `2월 16일  수요일 21:00` 까지 공부 정리한 내용 댓글로 남기기**

**Comment by devjun10** [comment]
[2주차 학습정리 내용](https://cookie-tin-8ec.notion.site/bbf399ff3aa64d1fb405fa42431c2edc)입니다.

**Comment by ak2j38** [comment]
2주차 내용정리 입니다!
https://velog.io/@ak2j38/운영체제-스터디-2.-컴퓨터시스템의-구조

**Comment by seyoung755** [comment]
2주차 내용정리 업로드 합니다~
https://velog.io/@seyoung755/운영체제-2주차-컴퓨터-시스템의-구조

**Comment by leekm0310** [comment]
2주차 내용정리 입니다!
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-2%EC%A3%BC%EC%B0%A8-%EC%BB%B4%ED%93%A8%ED%84%B0%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EA%B5%AC%EC%A1%B0

**Comment by nak253** [comment]
2주차 학습정리 링크입니다.
https://phase-bow-938.notion.site/59e17cce24604099bd8a128af0a5e900

**Comment by jinan159** [comment]
2주차 학습정리 링크입니다~!
https://jwkim96.tistory.com/219

**Comment by Louie-03** [comment]
[2주차 학습정리 링크](https://velog.io/@louie/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-2%EC%A3%BC%EC%B0%A8-%EC%BB%B4%ED%93%A8%ED%84%B0-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EA%B5%AC%EC%A1%B0)입니다.

**Comment by CMSSKKK** [comment]
[2주차 학습정리](https://velog.io/@cmsskkk/02) 제출입니다. 제출한다는걸 깜빡했네요 ㅠ
