### ISSUE TITLE
[3주차] 3. 프로세스 관리

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#3]
## 챕터 소개
- 프로그램의 실행 과정을 이해하고 커널이 가진 내용과 사용자 프로그램이 사용하는 함수를 알아본다.
- 프로세스의 개념, 상태, 문맥과 운영체제가 프로세스를 큐에 넣고 관리하는 형태에 대해 알아본다.
- 스케줄러의 세 종류인 장기, 단기, 중기 스케줄러에 대해 알아본다.
- 프로세스의 상태 변화와 프로세스 중 CPU 수행 단위인 스레드에 대해 알아본다.
- 프로세스의 생성에 있어 자식 프로세스가 부모 프로세스를 복제, 새로운 과정을 덮어씌우는 과정과 프로세스의 종료에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 2월 23일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by ak2j38** [comment]
아더 : 1, 2, 3강 중심으로 발표
루이 : 4, 5강 중심으로 발표하기로 결정되었습니다!

**Comment by ak2j38** [comment]
3주차 내용정리입니다.
https://velog.io/@ak2j38/운영체제-스터디-3.-프로세스-관리

**Comment by seyoung755** [comment]
3주차 정리 업로드합니다!
https://velog.io/@seyoung755/운영체제-3주차-프로세스-관리

**Comment by CMSSKKK** [comment]
3주차 정리 제출합니다!
[로니 03.프로세스관리](https://velog.io/@cmsskkk/03.-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EA%B4%80%EB%A6%AC)

**Comment by nak253** [comment]
3주차 학습정리 링크입니다.
https://phase-bow-938.notion.site/cdd558a539a9492eaae0b377f3e6d8dc

**Comment by leekm0310** [comment]
3주차 정리 링크 입니다!
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-3%EC%A3%BC%EC%B0%A8-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EA%B4%80%EB%A6%AC

**Comment by Louie-03** [comment]
[3주차 학습정리](https://nosy-frame-012.notion.site/8777863224db4ccbaa4d5418cf856a87)입니다!

**Comment by jinan159** [comment]
3주차 학습정리 업로드 합니다~!
https://jwkim96.tistory.com/224

**Comment by devjun10** [comment]
[3주차 학습정리 링크](https://cookie-tin-8ec.notion.site/7bbbef2e8f054b00b04698d3ca349d70) 입니다.
