### ISSUE TITLE
[4주차] 4. CPU 스케줄링

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#4]
## 챕터 소개
- 프로세스 생성과 종료에서 쓰이는 네 종류의 시스템 콜, 프로세스 간의 협력에 대해 알아본다.
- CPU 스케줄링과 디스패처가 필요한 이유와 개념에 대해 알아본다.
- CPU 스케줄링의 여러가지 알고리즘에 대해 알아본다.
- CPU 스케줄링의 여러가지 알고리즘 중 멀티레벨 큐와 멀티레벨 피드백 큐에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 3월 2일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by seyoung755** [comment]
4주차 정리 업로드합니다!
https://velog.io/@seyoung755/운영체제-4주차-CPU-스케줄링

**Comment by ak2j38** [comment]
4주차 내용 정리 링크입니다!
[4주차 내용 정리](https://velog.io/@ak2j38/운영체제-스터디-4.-CPU-스케줄링)

**Comment by CMSSKKK** [comment]
4주차 업로드합니다.
[cpu스케줄링](https://velog.io/@cmsskkk/04.-CPU-%EC%8A%A4%EC%BC%80%EC%A4%84%EB%A7%81)

**Comment by jinan159** [comment]
4주차 학습정리 업로드 합니다.
https://jwkim96.tistory.com/231

**Comment by leekm0310** [comment]
4주차 학습정리 업로드 합니다.
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-4%EC%A3%BC%EC%B0%A8-CPU-Scheduling

**Comment by nak253** [comment]
4주차 학습정리입니다.
https://phase-bow-938.notion.site/CPU-e77dec99a8484421ac4d38f614fb789d

**Comment by devjun10** [comment]
[4주차 학습정리](https://cookie-tin-8ec.notion.site/CPU-2756a18a4e74470b94844a4327d10bb1) 입니다.
