### ISSUE TITLE
[5주차] 5. 병행 제어 I

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#5]
## 챕터 소개

- 특수한 CPU Scheduling에 대해 알아본다.
- 동기화의 문제에 대해 알아본다.
- 동기화 문제의 해결 방법에 대해 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 3월 9일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by seyoung755** [comment]
5주차 정리 업로드합니다!!
https://velog.io/@seyoung755/운영체제-5주차-병행-제어-I

**Comment by ak2j38** [comment]
5주차 정리 링크입니다!
[병행제어](https://velog.io/@ak2j38/운영체제-스터디-5.-병행-제어)

**Comment by CMSSKKK** [comment]
5주차 업로드합니다.
[병행제어](https://velog.io/@cmsskkk/05.-%EB%B3%91%ED%96%89-%EC%A0%9C%EC%96%B4-1)

**Comment by leekm0310** [comment]
5주차 업로드 합니다. 어려웠습니다 ㅠㅠ 
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-5%EC%A3%BC%EC%B0%A8-Process-Synchronization

**Comment by nak253** [comment]
5주차 학습정리입니다.
https://phase-bow-938.notion.site/I-f325b210118e4bba8db77f02ce2a0133

**Comment by devjun10** [comment]
[5주차 학습정리](https://cookie-tin-8ec.notion.site/24475055596a4965abd30aa3b191778e) 입니다.

**Comment by jinan159** [comment]
학습정리 정리만 해놓고 제출한줄알고있었네요 ㅋㅋㅋ(못낼뻔..)
이번주 학습정리입니다!
https://jwkim96.tistory.com/237
