### ISSUE TITLE
[6주차] 6. 병행 제어 II

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#6]
## 챕터 소개

- 세마포 연산에서 생길 수 있는 문제인 데드락과 동기화와 관련된 전통적인 세 가지 문제에 대해 알아본다.
- 동기화 문제 해결을 위해 세마포 이외의 모니터 방식에 대해 알아본다.
- 데드락의 문제, 발생 조건, 처리방법 네 가지중 하나인 프리벤션을 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 3월 16일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by ak2j38** [comment]
6주차 내용정리입니다!
[병행제어2](https://velog.io/@ak2j38/운영체제-스터디-6.-병행-제어)

**Comment by seyoung755** [comment]
6주차 내용정리 업로드합니다!
[6주차 내용정리](https://velog.io/@seyoung755/운영체제-6주차-병행-제어-II)

**Comment by nak253** [comment]
6주차 학습 정리입니다.

[병행제어2](https://phase-bow-938.notion.site/II-7c2bcd94db104976b3bbdf1114d5a5a9)
[데드락](https://phase-bow-938.notion.site/f25c6253e9ba4e298d0f37f8eb1686bb)

**Comment by CMSSKKK** [comment]
6주차 내용정리 업로드합니다.
[병행제어2](https://velog.io/@cmsskkk/%EB%B3%91%ED%96%89-%EC%A0%9C%EC%96%B4-2)

저번주 발표자료 gif로 블로그에 올려봣습니다
[병행제어1발표자료](https://velog.io/@cmsskkk/%EB%B3%91%ED%96%89%EC%A0%9C%EC%96%B41-%EB%B0%9C%ED%91%9C%EC%9E%90%EB%A3%8C)

**Comment by leekm0310** [comment]
6주차 학습 정리 업로드 합니다.
[6주차정리](https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-6%EC%A3%BC%EC%B0%A8-%EB%B3%91%ED%96%89%EC%A0%9C%EC%96%B4)

**Comment by devjun10** [comment]
[6주차 학습정리](https://cookie-tin-8ec.notion.site/ac848127caff4105bd9763a7433ad6a7) 업로드 합니다.
