### ISSUE TITLE
[7주차] 7. 데드락 & 8. 메모리관리 I

### ISSUE THREAD

**Issue by jinan159** [codesquad-2022-be-study/OS-Study#7]
## 7. 데드락 챕터 소개

데드락 처리의 네 방법 중 남은 세 가지인 데드락 어보이던스, 디텍션 앤 리커버리, 이그노어런스를 배워본다.

## 8. 메모리관리 I 챕터 소개

메모리 주소의 종류와 주소 바인딩, 변환방식, 관련 용어, 물리적인 메모리 관리에 있어서 두 방식 중 하나인 연속할당을 알아본다.

각자 공부한 내용을 정리한 내용 혹은 링크를 댓글로 남겨주세요!🧑‍💻

🗓기한 : 3월 23일 수요일 21:00 까지 공부 정리한 내용 댓글로 남기기

**Comment by CMSSKKK** [comment]
[데드락](https://velog.io/@cmsskkk/%EB%B3%91%ED%96%89-%EC%A0%9C%EC%96%B4-2)
[메모리 관리 1](https://velog.io/@cmsskkk/%EB%A9%94%EB%AA%A8%EB%A6%AC-%EA%B4%80%EB%A6%AC-1)
7주차 정리 업로드합니다.

**Comment by ak2j38** [comment]
7주차 데드락&메모리 관리 정리입니다.
[데드락 & 메모리 관리](https://velog.io/@ak2j38/운영체제-스터디-7.-데드락과-메모리관리)

**Comment by seyoung755** [comment]
7주차 정리 업로드합니다.
[[7주차] - 데드락 & 메모리관리 I](https://velog.io/@seyoung755/운영체제-7주차-데드락-메모리관리-I)

**Comment by nak253** [comment]
7주차 학습 정리입니다.


[데드락](https://phase-bow-938.notion.site/f25c6253e9ba4e298d0f37f8eb1686bb)
[메모리관리](https://phase-bow-938.notion.site/0b58b4d7bcff4c608a48862584f1f316)

**Comment by devjun10** [comment]
7주차 [학습정리](https://cookie-tin-8ec.notion.site/be0606d929b94b86966e5499f02af13f) 입니다.

**Comment by jinan159** [comment]
이번주 학습정리 입니다
https://jwkim96.tistory.com/243

**Comment by leekm0310** [comment]
7주차 학습정리 입니다
https://velog.io/@becolorful/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EC%8A%A4%ED%84%B0%EB%94%94-7%EC%A3%BC%EC%B0%A8-%EB%8D%B0%EB%93%9C%EB%9D%BD-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EA%B4%80%EB%A6%AC-1
